check

diff --git a/.github/workflows/update-nightly.yml b/.github/workflows/update-nightly.yml
--- a/.github/workflows/update-nightly.yml
+++ b/.github/workflows/update-nightly.yml
@@ -44,10 +44,13 @@ jobs:
         run: yarn version --prerelease --preid=alpha --no-git --no-git-tag-version
 
       - name: Build NPM package
-        run: |
-          yarn pack | tee output.txt
-          FILE=$(grep -oE '[^ ]+\.tgz$' output.txt)
-          mv "$FILE" baileys-nightly.tgz
+       run: |
+         yarn pack | tee output.txt
+         FILE=$(grep -oE '[^ ]+\.tgz$' output.txt || true)
+         if [ -z "$FILE" ]; then
+           echo "Tarball not found!" && exit 1
+         fi
+         mv "$FILE" baileys-nightly.tgz
 
 
       - name: Generate Changelog
